services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=h.jrencontre@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reverse-proxy.rule=Host(`traefik.spotlive.fr`)"
      - "traefik.http.routers.reverse-proxy.entrypoints=web"
      - "traefik.http.routers.reverse-proxy.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.reverse-proxy.loadbalancer.server.port=8080"
      - "traefik.http.routers.reverse-proxy.tls=true"
      - "traefik.http.routers.reverse-proxy.tls.certresolver=myresolver"

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.spotlive.fr`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile.prod
    ports:
      - "8081:8081"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`app.spotlive.fr`)"
      - "traefik.http.routers.front.entrypoints=web"
      - "traefik.http.routers.front.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.front.loadbalancer.server.port=8081"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=myresolver"

networks:
  web:
    external: false