services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOSTNAME}`)"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${API_HOSTNAME}`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app/front
      - /app/front/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.services.front.loadbalancer.server.port=5173"