services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.prod
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 5s
      timeout: 20s
      retries: 10

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile.prod
    ports:
      - "8081:80"
    networks:
      - web
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 5s
      timeout: 20s
      retries: 10

networks:
  web:
    external: false