services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile.dev
    volumes:
      - ./front:/app/front
      - /app/front/node_modules
    ports:
      - "5173:5173"
    networks:
      - web

  db:
    image: postgres:17.2
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - web

networks:
  web:
    external: false

volumes:
  postgres_data: