version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app/front
      - /app/front/node_modules