services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    networks:
      - web

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile.dev
    ports:
      - "5173:5173"
    networks:
      - web

networks:
  web:
    external: false