FROM node:lts-alpine AS build
WORKDIR /app/front
COPY ./front/package*.json ./
RUN npm install
COPY ./front ./
RUN npm run build

FROM nginx:stable-alpine AS release
COPY --from=build /app/front/dist /usr/share/nginx/html
COPY ./docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
