name: Test Frontend

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test_front:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: front/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - run: cd front && npm run test
        name: Run Tests
