name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  call-install-dependencies:
    uses: ./.github/workflows/front/install-dependencies.yml

  call-build-frontend:
    needs: call-install-dependencies
    uses: ./.github/workflows/front/build.yml
