name: Install Frontend Dependencies

on:
  workflow_call:

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: front/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - run: cd front && npm ci
        name: Install dependencies
