name: test

on:
  push:
    branches: [ "main", "develop", "preprod" ]
  pull_request:
    branches: [ "main", "develop", "preprod" ]

jobs:
  backend-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd spotlive/api && npm ci
    - run: cd spotlive/api && npm run build --if-present
    - run: cd spotlive/api && npm test

  frontend-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd spotlive/front && npm ci
    - run: cd spotlive/front && npm run build --if-present
    - run: cd spotlive/front && npm test
